// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhkxAfL66iLfNBaYhaYT03Q7Ux98ZL5yQ',
    appId: '1:568380153576:web:b2b8df190452f76d0c335d',
    messagingSenderId: '568380153576',
    projectId: 'chat-app-btbs',
    authDomain: 'chat-app-btbs.firebaseapp.com',
    storageBucket: 'chat-app-btbs.appspot.com',
    measurementId: 'G-XRLXNN5T5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAle_QoSIFEJA0dqof9zGXV_6Yld62azAI',
    appId: '1:568380153576:android:61342f95b28847f60c335d',
    messagingSenderId: '568380153576',
    projectId: 'chat-app-btbs',
    storageBucket: 'chat-app-btbs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA80lnkunsdLzvPyqwPW3wtoJh8NWAwbgs',
    appId: '1:568380153576:ios:45e49387f3a4b75b0c335d',
    messagingSenderId: '568380153576',
    projectId: 'chat-app-btbs',
    storageBucket: 'chat-app-btbs.appspot.com',
    iosBundleId: 'com.example.chatAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA80lnkunsdLzvPyqwPW3wtoJh8NWAwbgs',
    appId: '1:568380153576:ios:28f1b9d7f78725ae0c335d',
    messagingSenderId: '568380153576',
    projectId: 'chat-app-btbs',
    storageBucket: 'chat-app-btbs.appspot.com',
    iosBundleId: 'com.example.chatAppFlutter.RunnerTests',
  );
}
